// 로그인
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// 에러 클리어
export const CLEAR_ERROR_REQUEST = "CLEAR_ERROR_REQUEST";
export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS";
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE";

// 회원가입
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

// 로그인된 유저 정보 불러오기
export const USER_LOADING_REQUEST = "USER_LOADING_REQUEST";
export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS";
export const USER_LOADING_FAILURE = "USER_LOADING_FAILURE";

// 로그아웃
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// 글 작성시 포인트 +5
export const GET_POINT_WHEN_POST_REQUEST = "GET_POINT_WHEN_POST_REQUEST";
export const GET_POINT_WHEN_POST_SUCCESS = "GET_POINT_WHEN_POST_SUCCESS";
export const GET_POINT_WHEN_POST_FAILURE = "GET_POINT_WHEN_POST_FAILURE";

//
//
// postReducer, postSaga

// 포스트 컨텐츠 불러오기
export const POST_CONTENT_REQUEST = "POST_CONTENT_REQUEST";
export const POST_CONTENT_SUCCESS = "POST_CONTENT_SUCCESS";
export const POST_CONTENT_FAILURE = "POST_CONTENT_FAILURE";

// 추천 기능
export const POST_UP_VOTE_REQUEST = "POST_UP_VOTE_REQUEST";
export const POST_UP_VOTE_SUCCESS = "POST_UP_VOTE_SUCCESS";
export const POST_UP_VOTE_FAILURE = "POST_UP_VOTE_FAILURE";

// 추천 기능
export const POST_DOWN_VOTE_REQUEST = "POST_DOWN_VOTE_REQUEST";
export const POST_DOWN_VOTE_SUCCESS = "POST_DOWN_VOTE_SUCCESS";
export const POST_DOWN_VOTE_FAILURE = "POST_DOWN_VOTE_FAILURE";
